title: Title
subtitle: Subtitle
author: Mig Reyes
description: Description.

source: .
destination: public
exclude: [_drafts, _site, public, Gemfile, Gemfile.lock, Rakefile, README.md]

permalink: /:categories/:title
markdown: rdiscount
pygments: true